* add abbility to skip OS installation * bugfixing

diff --git a/install-test b/install-test
--- a/install-test
+++ b/install-test
@@ -2,13 +2,16 @@
 echo "Starting script $0 $@"
 echo "Deploying to node: $NODE_NAME"
 
-XCAT="jenkins@openstack-xcat.vm.griddynamics.net"
-
-rsync -avz --del ./altai-xcat $RUN:~/
-if ! ssh $XCAT ~/altai-xcat/spawn_node $NODE_NAME
-then 
-    echo "Failed to spawn $NODE_NAME"
-    exit 1
+if [ "x$OS_MODE" == "xskip" ]; then
+    echo "Skipping node installation"
+else
+    XCAT="jenkins@openstack-xcat.vm.griddynamics.net"
+    rsync -avz --del ./altai-xcat $XCAT:~/
+    if ! ssh $XCAT ./altai-xcat/spawn_node "$NODE_NAME" "$OS_MODE"
+    then 
+        echo "Failed to spawn $NODE_NAME"
+        exit 1
+    fi
 fi
 
 if [ "x$MODE" == "xplain" ]; then
@@ -23,6 +26,6 @@ fi
 
 RUN="root@$NODE_IP"
 scp -r ./altai-deploy-scripts/ "$RUN":
-env | ssh $RUN "cat > ./altai-deploy-scripts/env; ./altai-deploy-scripts/install-nodes"
+declare -p | ssh $RUN "cat > ./altai-deploy-scripts/environment; ./altai-deploy-scripts/install-nodes"
 retval=$?
 exit $retval
